### ISSUE TITLE
Wine 9.0 Released

### ISSUE THREAD

**Issue by james2432** [flathub/org.winehq.Wine#107]
https://www.winehq.org/news/2024011601

As this is a stable release, the package will have to be updated

**Comment by james2432** [comment]
Related to PR: ~~https://github.com/flathub/org.winehq.Wine/pull/106#issue-2085020200~~ 

https://github.com/flathub/org.winehq.Wine/pull/111

**Comment by Docmine17** [comment]
👀

**Comment by james2432** [comment]
@gasinvein is this project still being maintained?

**Comment by bbhtt** [comment]
https://github.com/flathub/org.winehq.Wine/pull/111
