### ISSUE TITLE
can't run apps after switching from Linux Mint repo Wine 9.0 to Flatpak Wine 9.0

### ISSUE THREAD

**Issue by g1001** [flathub/org.winehq.Wine#115]
Don't know if this is the right place to ask. Uninstalled the (working) Wine from Mint and installed the Flatpak from flathub with the command line. 

I also noted that my ~/.wine directory was unchanged by the Wine switch.

However I cannot now run either of the Windows apps I had been able to run under the Mint Wine. I'm probably doing something stupid but I need a push in the right direction.

Here's a few sample commands I've tried and the results (with the "fixme"s mostly left out):

george@L440:~/.wine/drive_c/Program Files/IrfanView$ flatpak run org.winehq.Wine ./i_view64.exe

wine: failed to open "./i_view64.exe": c0000135

--- try again without the "./" in front of the executable:

~/.wine/drive_c/Program Files/IrfanView$ flatpak run org.winehq.Wine i_view64.exe

Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

--- try with full unix-style path

george@L440:~/.wine/drive_c/Program Files/IrfanView$ flatpak run org.winehq.Wine start /unix "/home/george/.wine/drive_c/Program Files/IrfanView/.i_view64.exe"

0114:err:exec:SHELL_ExecuteW cannot set directory L"L:\\george\\.wine\\drive_c\\Program Files\\IrfanView"
0114:fixme:exec:SHELL_execute flags ignored: 0x00000100
0114:err:exec:SHELL_ExecuteW cannot set directory L"L:\\george\\.wine\\drive_c\\Program Files\\IrfanView"
0114:fixme:exec:SHELL_execute flags ignored: 0x00000100
0114:err:exec:SHELL_ExecuteW cannot set directory L"L:\\george\\.wine\\drive_c\\Program Files\\IrfanView"

Any help appreciated.

**Comment by Erick555** [comment]
You need to copy all `~/.wine` contents to `~/.var/app/org.winehq.Wine/data/wine`

**Comment by g1001** [comment]
Thanks! That did it.

I thought it would be something easy.

Was there someplace I missed looking at that would have told me this?

For anyone who comes here later, note that the .wine in ~ REPLACES the (no-dot) wine folder under ~/.var/app/org.winehq.Wine/data. I did it this way, while bash was in ~/.var/app/org.winehq.Wine/data:

mv wine wine.sav   # as a backup & also to get it out of the way
cp -a ~/.wine ~/.var/app/org.winehq.Wine/data/
mv .wine wine

When you're happy it works, you can remove the wine.sav.

Thanks again!
