### ISSUE TITLE
Include samba winbind runtime with the Flatpak

### ISSUE THREAD

**Issue by rashidi77** [flathub/org.winehq.Wine#3]
Microsoft Office 2010 and many other applications require samba winbind package to work properly. The current flatpak does not have this dependency included. It would be better if you offer this as a runtime dependency.

**Comment by gasinvein** [comment]
Thanks for reporting this. Are you completely sure that it is missing samba what is causing errors, or you've just seen a samba-related error/warning on wine console output?

**Comment by Erick555** [comment]
MS office 2010 would hang on startup without winbind.

**Comment by gasinvein** [comment]
Ok, let's try to add Samba: #6
Please test it and report back if fixes the issue, ideally with both 32- and 64-bit MSO.

**Comment by rashidi77** [comment]
> Ok, let's try to add Samba: #6 Please test it and report back if fixes the issue, ideally with both 32- and 64-bit MSO.

How do I test it? I am a total newb in git and flatpaks.

**Comment by gasinvein** [comment]
> > Ok, let's try to add Samba: #6 Please test it and report back if fixes the issue, ideally with both 32- and 64-bit MSO.
> 
> How do I test it? I am a total newb in git and flatpaks.

Run [this](https://github.com/flathub/org.winehq.Wine/pull/6#issuecomment-1066115630) command, then run the test build as `flatpak run org.winehq.Wine//test ...`

**Comment by rashidi77** [comment]
> Run [this](https://github.com/flathub/org.winehq.Wine/pull/6#issuecomment-1066115630) command

It says: 
`error: Can't load uri https://dl.flathub.org/build-repo/79353/org.winehq.Wine.flatpakref: Server returned status 404: Not Found
`

**Comment by gasinvein** [comment]
Probably the test build was deleted. I've requested a new one, wait for it.

**Comment by brunoais** [comment]
@rashidi77 Any results?

**Comment by rashidi77** [comment]
> @rashidi77 Any results?

I forgot to test the build that day, it seems the build is deleted again.

**Comment by gasinvein** [comment]
@rashidi77 [Here](https://github.com/flathub/org.winehq.Wine/pull/6#issuecomment-1080439631) is a new one.

**Comment by rashidi77** [comment]
> @rashidi77 [Here](https://github.com/flathub/org.winehq.Wine/pull/6#issuecomment-1080439631) is a new one.

It worked with MS Office Pro 2010. Tested on Fedora Silverblue 36. I did not  try the installer by the way, but I used an already configured wineprefix. Word and Excel worked, but Powerpoint crushed.

**Comment by Erick555** [comment]
Is Powerpoint crash related to flatpak environment?

**Comment by rashidi77** [comment]
> Is Powerpoint crash related to flatpak environment?

I don't think so, I think something is wrong with my wineprefix. It crashes with the native wine packages too. It seems the print preview dialogue is causing crashes too in Word and Excel. I did not spent my time to debug it however.

**Comment by Erick555** [comment]
Ok. I still think 32bit samba may be [unecessary](https://github.com/flathub/org.winehq.Wine/pull/6#issuecomment-1066118083).

**Comment by rashidi77** [comment]
> Ok. I still think 32bit samba may be [unecessary](https://github.com/flathub/org.winehq.Wine/pull/6#issuecomment-1066118083).

Okay. It's up to you if you include it or not. It might be helpful or not, it seems Bottles developers included samba with their flatpak. Here is the MR : 
https://github.com/bottlesdevs/Bottles/pull/1089

I tested it today, it works.

**Comment by Erick555** [comment]
Thx. They didn't include 32bit so if that works for you then it proves 32bit is not necessary. @gasinvein could you drop 32bit parts from samba PR?

**Comment by gasinvein** [comment]
@Erick555 I believe we should keep it, at least for symmetry (so both 32- and 64-bit wine are built with the same dependency set).

@rashidi77 Testing 32-bit MSO (IIRC version 2010 still supported it) would be very much appreciated.

**Comment by rashidi77** [comment]
> @Erick555 I believe we should keep it, at least for symmetry (so both 32- and 64-bit wine are built with the same dependency set).
> 
> @rashidi77 Testing 32-bit MSO (IIRC version 2010 still supported it) would be very much appreciated.

If I understand properly you are asking me if I can test Microsoft Office 2010 32bit version. I only tested the 32bit version. I don't know about the 64 bit as I could not find a tutorial how to install the 64 bit. [I'm not native in English, so my understanding can be wrong.]

**Comment by Erick555** [comment]
Yeah 64bit offices tended to be broken and still could be so 32bit is what most people use.
