### ISSUE TITLE
Include runtime dependencies for winetricks

### ISSUE THREAD

**Issue by helkaluin** [flathub/org.winehq.Wine#37]
As per https://wiki.winehq.org/Winetricks, the script depends on other programs:

* cabextract
* unzip
* p7zip
* wget/curl

I don't believe cabextract and p7zip are included in this Flatpak currently. The lack of cabextract in particular means corefonts can't be installed.

**Comment by gasinvein** [comment]
`cabextract` and `p7zip` are there, while `unzip`, `curl` and `wget` are available in the runtime.

**Comment by helkaluin** [comment]
Wait, if they're there then why does invoking winetricks corefonts within the Flatpak fail due to cabextract returning command not found

**Comment by gasinvein** [comment]
It doesn't fail for me. You can check if cabextract is there and works with `flatpak run --command=cabextract org.winehq.Wine//stable-22.08 --version`

**Comment by helkaluin** [comment]
Weird, now it's there when it failed before I submitted this.
Sorry for wasting your time.
