### ISSUE TITLE
Availability of FSync/Low Fragmentation Heap patches?

### ISSUE THREAD

**Issue by lunarlattice0** [flathub/org.winehq.Wine#42]
Hi, I'm a maintainer for the net.brinkervii.grapejuice which now uses org.winehq.Wine as a base. Previously, we were using a pre-compiled version of wine, but have switched to this flatpak for reproducible builds of wine. Although our performance has been decent, I wanted to ask whether FSync and the Low Fragmentation Heap patches have been implemented into this flatpak, or whether you would be open to integrating them.

Thanks!

**Comment by gasinvein** [comment]
This is just vanilla wine-stable, without any patches (except for [this](https://github.com/flathub/org.winehq.Wine/blob/branch/stable-22.08/patches/wine/loader-prefer-winedllpath.patch) flatpak-specific one we need for DDL extensions to function).
Other wine builds on different branches of this app are entirely technically possible, but at submission of this app, we decided to stick to current wine stable build only, at least for now. See #20 for similar (and more general) question and discussion.

**Comment by lunarlattice0** [comment]
Thanks for your response.
