### ISSUE TITLE
Wine-8.0 Stable [update]

### ISSUE THREAD

**Issue by fastrizwaan** [flathub/org.winehq.Wine#46]
Hi,
Wine 8 has better compatiblity than 7.0, as it includes media foundation fixes. Kindly update to 8.0 stable. Thanks.
```
url: https://dl.winehq.org/wine/source/8.0/wine-8.0.tar.xz
sha256: 0272c20938f8721ae4510afaa8b36037457dd57661e4d664231079b9e91c792e
```

**Comment by jekanev** [comment]
> Hi, Wine 8 has better compatiblity than 7.0, as it includes media foundation fixes. Kindly update to 8.0 stable. Thanks.
> 
> ```
> url: https://dl.winehq.org/wine/source/8.0/wine-8.0.tar.xz
> sha256: 0272c20938f8721ae4510afaa8b36037457dd57661e4d664231079b9e91c792e
> ```

Hi, i think there is some tests before 8.0 will be released, you can look Pull requests section and install test version 8.0 there is command provided `flatpak install --user https://dl.flathub.org/build-repo/3110/org.winehq.Wine.flatpakref` its last one ive seen.

**Comment by gasinvein** [comment]
Please install a test build from #45 and report there if it works. I don't have a Linux PC at hand right now, so can't check everything myself.

**Comment by fastrizwaan** [comment]
```
[rizvan@localhost ~]$ flatpak run org.winehq.Wine --version
wine-8.0
[rizvan@localhost ~]$ flatpak run --command=winecfg org.winehq.Wine 
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00d8:err:module:LdrInitializeThunk "msacm32.dll" failed to initialize, aborting
00d8:err:module:LdrInitializeThunk Initializing dlls for L"C:\\windows\\syswow64\\winecfg.exe" failed, status c0000005


```

**Comment by Erick555** [comment]
`flatpak run --command=winecfg org.winehq.Wine` works here for 8.0.

**Comment by gasinvein** [comment]
> ```
> [rizvan@localhost ~]$ flatpak run org.winehq.Wine --version
> wine-8.0
> [rizvan@localhost ~]$ flatpak run --command=winecfg org.winehq.Wine 
> 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> 00d8:err:module:LdrInitializeThunk "msacm32.dll" failed to initialize, aborting
> 00d8:err:module:LdrInitializeThunk Initializing dlls for L"C:\\windows\\syswow64\\winecfg.exe" failed, status c0000005
> ```

Try with a clean Wine prefix, e.g. `flatpak run --env=WINEPREFIX=/tmp/wineprefix --command=winecfg org.winehq.Wine`

**Comment by fastrizwaan** [comment]
`flatpak run --env=WINEPREFIX=/tmp/wineprefix --command=winecfg org.winehq.Wine`

this works!

**Comment by gasinvein** [comment]
Ok, let's merge.
