### ISSUE TITLE
fix: unable to find the page

### ISSUE THREAD

**Issue by jjangga0214** [flathub/org.winehq.Wine#48]
Hi!
I am seeing NOT FOUND page. 
Would this be fixed? 
Thanks :) 

https://flathub.org/apps/details/org.winehq.Wine

<img width="1000" alt="스크린샷 2023-02-14 오후 4 44 07" src="https://user-images.githubusercontent.com/28584151/218671443-c4b3f9f7-d712-4bc5-a55e-31373ced2084.png">

**Comment by gasinvein** [comment]
No, Wine itself is a command-line program, which Flathub's web front-end currently doesn't show. See flathub/website#53
