### ISSUE TITLE
Wine 8.5 released

### ISSUE THREAD

**Issue by farribeiro** [flathub/org.winehq.Wine#54]
Hello

I've noticed that the update system is currently only detecting major releases of Wine, which means that any intermediate versions of the 8.x series are not being picked up. This could potentially lead to users missing out on important bug fixes and improvements that are present in those intermediate releases

PS: The latest release of Wine in announcement https://www.winehq.org/news/

Best regards,
Fabio

**Comment by Erick555** [comment]
In the announcement you can read:

> The Wine **development** release 8.5 is now available.

while flatpak follow only wine **stable** releases where 8.0 is the latest. See also https://github.com/flathub/org.winehq.Wine/issues/20

**Comment by farribeiro** [comment]
Thanks for clarifying that the version is not stable
