### ISSUE TITLE
/lib/ld-linux.so.2: could not open, i386-linux-gnu/ld-linux.so.2 file not found

### ISSUE THREAD

**Issue by jcleng** [flathub/org.winehq.Wine#61]
https://github.com/fastrizwaan/flatpak-wine/issues/19#event-9323366264

**Comment by gasinvein** [comment]
`org.freedesktop.Platform.Compat.i386` isn't installed?

**Comment by jcleng** [comment]
> `org.freedesktop.Platform.Compat.i386` isn't installed?

maybe yes, but run `flatpak update --commit=a73797d2...` can installed

**Comment by gasinvein** [comment]
I don't know what, how and from where you have installed, and I can't really guess any further.
