### ISSUE TITLE
How do I update from version 7 to version 8?

### ISSUE THREAD

**Issue by sunhasgothishaton** [flathub/org.winehq.Wine#62]
Hi

I have wine version 7 installed, when I run flatpak update it doesn't get upgraded to version 8. How do I upgrade flatpak wine to version 8?

Thanks,
Rob

**Comment by Erick555** [comment]
Did you install  `org.winehq.Wine ` or some other app that bundles it? The former should be at version 8 automatically after update but the latter needs rebuild on flathub first.

**Comment by sunhasgothishaton** [comment]
When I first installed wine, I ran `flatpak install org.winehq.Wine`. Flatpak reported version 7 branch stable-21.08 was installed.

When I run `flatpak update` nothing is updated even though version 8 is available.

Now when I run `flatpak install org.winehq.Wine` it offers me 2 options :
  1) app/org.winehq.Wine/x86_64/stable-22.08
  2) app/org.winehq.Wine/x86_64/stable-21.08

**Comment by Erick555** [comment]
`app/org.winehq.Wine/x86_64/stable-22.08` is the latest one which offers wine 8. Yo may remove the other one.

**Comment by sunhasgothishaton** [comment]
Great, thank. I've got wine 8 installed now.

Will I have to do the same (another `flatpak install`) when wine 9 is released, instead of `flatpak update`?

**Comment by Erick555** [comment]
It's not guaranteed but most likely there will be stable-23.08 branch at wine 9 release time and the stable-22.08 will be orphaned.

**Comment by sunhasgothishaton** [comment]
Great, thanks for your help
