### ISSUE TITLE
Cannot find package in flathub

### ISSUE THREAD

**Issue by brunoais** [flathub/org.winehq.Wine#72]
When I try to find this on flathub I get a status 404 not found.
![image](https://github.com/flathub/org.winehq.Wine/assets/639467/370d2da6-360b-4c83-a937-822e1bbcd210)

Is this expected?

**Comment by Erick555** [comment]
yes, wine is in essence a CLI tool and flathub store doesn't show CLI flatpaks.

**Comment by brunoais** [comment]
In that case, I think it would make sense to use a different url in the repository about
![image](https://github.com/flathub/org.winehq.Wine/assets/639467/131d80d1-72e1-469b-918a-fa8cc3f00d48)

**Comment by Erick555** [comment]
this url is created automatically by flathub even when it points to nothing

**Comment by brunoais** [comment]
I see... Then it's complicated and now I understand the issue. Thank you. I guess there's nothing that can be done about that.
Thanks for answering.
