### ISSUE TITLE
FreeDesktop 23.08

### ISSUE THREAD

**Issue by Doomsdayrs** [flathub/org.winehq.Wine#85]
FreeDesktop 23.08 is out, and 21.08 is EOL. May a maintainer please create the branch for it?

I am considering this a blocker for [itch](https://github.com/flathub/io.itch.itch/pull/9), do tell me if it is not.

**Comment by gasinvein** [comment]
I've pushed a build fix for 23.08, the branch should become available soon. If you experience any problems with it, please report them as separate issues.

@barthalion Please make the `branch/stable-23.08` branch default.

**Comment by tim77** [comment]
DXVK and libs also need to rebuild upon new `23.08`.
