### ISSUE TITLE
Why does this app contain a copy of libudev.so?

### ISSUE THREAD

**Issue by fkrull** [flathub/org.winehq.Wine#88]
This Flatpak contains copies of libudev.so.1.6.3 in /app/lib and /app/lib32 even though (current versions of) the Freedesktop runtimes already ship with libudev. This  breaks components of the runtime built against the runtime's newer version of libudev because the older version from the app gets picked up instead. Specifically this happened in the Lutris Flatpak: https://github.com/flathub/net.lutris.Lutris/issues/364

Is this dependency important? It looks like it was added over two years ago: https://github.com/flathub/org.winehq.Wine/commit/1e2a15f8f0203d3d18009fd112909e437db4b0a1 I tried removing it and the Flatpak still builds.

**Comment by gasinvein** [comment]
Most likely the bundled libudev is a leftover from previous runtime versions that didn't have one.
Mind sending a pr removing the eudev module?

**Comment by strycore** [comment]
I was worried that the Freedesktop version of udev would not provide the 32bit version of udev, which is still a requirement for Wine (we redid the build setup recently based on Wine's own build scripts and udev is still there.
Hopefully this won't cause any issue.

**Comment by gasinvein** [comment]
@strycore The `.Compat.i386` extension should provide the exact same libraries as the native x86_64 runtime has.
