### ISSUE TITLE
Is there any way to disable DXVK on the wineprefix?

### ISSUE THREAD

**Issue by matheuswillder** [flathub/org.winehq.Wine#94]
Basically what the title says. I tried using this Flatpak months ago but all the games I tested at the time ran extremely slow and unstable, which didn't happen with regular Wine or Bottles. I decided to test it again now but I got the same result. Trying to investigate, I saw that when I run some game through **flatpak run org.winehq.Wine path-to-the-game.exe** the output in the Terminal/Console have lines related to DXVK and Vulkan, which the old iGPU I use doesn't support, so I think that DXVK/Vulkan is running in software renderer or something like that, which explains the slowness and instability.

However, I don't see any overrides to the DXVK .dlls in **flatpak run org.winehq.Wine winecfg**, nor have I had success just deleting the D3D .dlls from the wineprefix and trying to recreate them with **flatpak run org.winehq.Wine wineboot --update**, so I wonder if there is any way to disable it.

I can post the Terminal/Console outputs I get when I try to run a game, I'm not posting them right now because I don't know if it's a useful info.

**Comment by Erick555** [comment]
Did you try `flatpak remove org.winehq.Wine.DLLs.dxvk` then cleaning or creating new wineprefix?

**Comment by matheuswillder** [comment]
I hadn't thought of that before, this worked! Thank you for your help!

Edit: just in case anyone else come to this issue with the same problem, also use **flatpak mask org.winehq.Wine.DLLs.dxvk** should prevent the runtime to being installed again after an **flatpak update**, however there seems to be a bug in flatpak mask as [seen here](https://github.com/flatpak/flatpak/issues/4615), so I don't know if it should work until it is fixed (but I haven't tested it yet as I was just looking for the options to prevent the runtime from being installed again in the [docs](https://docs.flatpak.org/en/latest/flatpak-command-reference.html)).
